## Configuração Default da Aplicação ##
server:
  ## HTTP Server port
  port: 8080

## Eureka - Service Discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/${eureka.name}/
    register-with-eureka: true

## Config Application and Database
spring:
  application:
    name: gateway

  ## Routes MS
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/authentication/**
        - id: accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
        - id: feed
          uri: lb://feed
          predicates:
            - Path=/feed/**
        - id: notifications
          uri: lb://notifications
          predicates:
            - Path=/notifications/**
        - id: directmessages
          uri: lb://directmessages
          predicates:
            - Path=/directmessages/**

## Swagger OpenAPI v3 Springdoc ##
springdoc:
  webjars:
    prefix: /apis
  api-docs:
    groups:
      enabled: true # Habilita acessar swagger dos microserviços através do gateway
  swagger-ui:
    doc-expansion: none
    groups-order: asc
    tags-sorter: 'alpha' # Ordena as tags alfabeticamente
    operations-sorter: 'alpha' # Ordena as operations alfabeticamente
    path: /swagger-ui/
    urls: # Caminho do 'api-docs' de cada microserviço a ser exibido na lista
      - name: authentication
        url: /authentication/v3/api-docs
      - name: accounts
        url: /accounts/v3/api-docs
      - name: feed
        url: /feed/v3/api-docs
      - name: notifications
        url: /notifications/v3/api-docs
      - name: directmessages
        url: /directmessages/v3/api-docs